<?php

namespace Agence\AgenceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MediaEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaEventRepository extends EntityRepository
{
}
