danseuse_galerie:
    path:     /
    defaults: { _controller: "AgenceBundle:Galerie:index" }

danseuse_galerie_new:
    path:     /new
    defaults: { _controller: "AgenceBundle:Galerie:create" }

danseuse_galerie_create:
    path:     /create
    defaults: { _controller: "AgenceBundle:Galerie:create" }
    methods:  POST

danseuse_galerie_delete:
    path:     /{id}/delete
    defaults: { _controller: "AgenceBundle:Galerie:delete" }
    methods:  [POST, DELETE]