services:
    tva:
        class: Agence\AgenceBundle\Twig\Extension\TvaExtension
        tags:
            - { name: twig.extension }

    montantTva:
        class: Agence\AgenceBundle\Twig\Extension\MontantTvaExtension
        tags:
            - { name: twig.extension }

    redirectionListener:
      class: Agence\AgenceBundle\Listener\RedirectionListener
      arguments: [@service_container, @session]
      tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    setNewReference:
      class: Agence\AgenceBundle\Services\GetReference
      arguments: [@security.context, @doctrine.orm.entity_manager]

    setNewFacture:
      class: Agence\AgenceBundle\Services\GetFacture
      arguments: [@service_container]